export async function onRequestPost(context) {

    try {

        const data = await context.request.json();


        const name = String(data.name || "").trim();
        const email = String(data.email || "").trim();
        const phone = String(data.phone || "").trim();
        const business = String(data.business || "").trim();
        const service = String(data.service || "").trim();
        const contactMethod =
            String(data["contact-method"] || "Email").trim();

        const message = String(data.message || "").trim();


        // Required fields
        if (!name || !email || !service || !message) {

            return Response.json(
                {
                    success: false,
                    message: "Please complete all required fields."
                },
                {
                    status: 400
                }
            );

        }


        // Basic email validation
        const emailPattern =
            /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

        if (!emailPattern.test(email)) {

            return Response.json(
                {
                    success: false,
                    message: "Please enter a valid email address."
                },
                {
                    status: 400
                }
            );

        }


        // Prevent extremely large submissions
        if (message.length > 5000) {

            return Response.json(
                {
                    success: false,
                    message: "Your message is too long."
                },
                {
                    status: 400
                }
            );

        }


        // Keep subject line clean
        const cleanName =
            name.replace(/[\r\n]/g, " ");

        const cleanService =
            service.replace(/[\r\n]/g, " ");


        const emailBody = `
NEW DYMONND IT SUPPORT REQUEST

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CUSTOMER

Name:
${name}

Email:
${email}

Phone:
${phone || "Not provided"}

Business / Organisation:
${business || "Not provided"}

Preferred Contact:
${contactMethod}


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SERVICE

${service}


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

MESSAGE

${message}


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Submitted via:
dymonndit.com

This message was generated by the
Dymonnd IT website support form.
        `.trim();


        const resendResponse =
            await fetch(
                "https://api.resend.com/emails",
                {
                    method: "POST",

                    headers: {
                        "Authorization":
                            `Bearer ${context.env.RESEND_API_KEY}`,

                        "Content-Type":
                            "application/json"
                    },

                    body: JSON.stringify({

                        from:
                            "Dymonnd IT Website <website@forms.dymonndit.com>",

                        to: [
                            "support@dymonndit.com"
                        ],

                        reply_to:
                            email,

                        subject:
                            `New ${cleanService} request - ${cleanName}`,

                        text:
                            emailBody

                    })
                }
            );


        const resendResult =
            await resendResponse.json();


        if (!resendResponse.ok) {

            console.error(
                "Resend error:",
                resendResult
            );


            return Response.json(
                {
                    success: false,
                    message:
                        "Unable to send your request."
                },
                {
                    status: 500
                }
            );

        }


        return Response.json(
            {
                success: true,
                message:
                    "Your support request has been sent."
            },
            {
                status: 200
            }
        );


    } catch (error) {

        console.error(
            "Support form error:",
            error
        );


        return Response.json(
            {
                success: false,
                message:
                    "Something went wrong while sending your request."
            },
            {
                status: 500
            }
        );

    }

}